network:
        host:   your.server.org
        port:   6667

channel:  "#channel"
     
rss:
        url:    "http://your.rss.feed/url"
        freq:   60

quakeAuth:
        authName:   quakeNetAuthName        
        authPass:   quakeNetAuthPassword

nickname:  "yournick"               
realname:  "yourname"
build:     "unstable dev build"

notifyComics:
        comics:
            Gunnerkrigg Court : {
                0: [08, 00],
                2: [08, 00],
                4: [08, 00]
                }
        defaultComic: "Gunnerkrigg Court"
